
# Use this file to customize your demo.
# Write computer specific settings in config.local.yml, which won't be versioned.
demo:
  audioTool: shader
  name: template
  glslversion: 330
shader:
  globals:
    float:
      - TAU = 6.283
