# Use this file to customize your demo.
# Write computer specific settings in config.local.yml, which won't be versioned.
demo:
  audioTool: oidos
  name: template
  glslVersion: 330
shader:
  globals:
    float:
